### PR TITLE
Per client authorization

### PR DESCRIPTION
**Pull request by aurelien-semence**
Just add `clientID` in `PasswordAuthorizationHandler` if we need to customize password authorization per client.

### CODE REVIEW

**Review by realbucksavage — CHANGES_REQUESTED** [review]
@aurelien-semence can you please make `clientID` the first parameter so that the sequence written in other "handler" methods is followed?

Other than that, it looks good to me.

**Comment by realbucksavage** [comment]
@aurelien-semence seems like you missed a change on line 360 in `server/server.go`.

Also, since you're always passing `clientID` to the handler, it pretty much makes it a value that is always present. That was my reasoning behind rearranging the sequence.

**Comment by aurelien-semence** [comment]
@realbucksavage fixed

**Review by realbucksavage — APPROVED** [review]
This looks good to me. @LyricTian this can be merged.

**Pull request merged**
